# Generated by Django 5.2.4 on 2025-07-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99)),
                ('duration_in_months', models.IntegerField()),
                ('description', models.TextField()),
                ('tools_using', models.TextField()),
            ],
        ),
    ]
