# Generated by Django 5.2.4 on 2025-07-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_courses_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='cost',
            field=models.IntegerField(default=20000),
        ),
    ]
